# Generated by Django 5.1.4 on 2026-04-30 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_create_role_groups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('review', 'Under review'), ('closed', 'Closed')], default='open', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-year', '-month'),
            },
        ),
        migrations.CreateModel(
            name='SplitRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='split_rule', to='periods.month')),
            ],
        ),
        migrations.CreateModel(
            name='SplitShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_company', models.BooleanField(default=False)),
                ('percent', models.PositiveSmallIntegerField()),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='split_shares', to='accounts.person')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='periods.splitrule')),
            ],
            options={
                'ordering': ('-is_company', 'person__name'),
            },
        ),
        migrations.AddConstraint(
            model_name='month',
            constraint=models.UniqueConstraint(fields=('year', 'month'), name='periods_month_unique'),
        ),
        migrations.AddConstraint(
            model_name='month',
            constraint=models.CheckConstraint(condition=models.Q(('month__gte', 1), ('month__lte', 12)), name='periods_month_range'),
        ),
        migrations.AddConstraint(
            model_name='splitshare',
            constraint=models.CheckConstraint(condition=models.Q(('percent__gte', 0), ('percent__lte', 100)), name='periods_share_percent_range'),
        ),
        migrations.AddConstraint(
            model_name='splitshare',
            constraint=models.UniqueConstraint(condition=models.Q(('person__isnull', False)), fields=('rule', 'person'), name='periods_share_unique_person'),
        ),
        migrations.AddConstraint(
            model_name='splitshare',
            constraint=models.UniqueConstraint(condition=models.Q(('is_company', True)), fields=('rule',), name='periods_share_unique_company'),
        ),
    ]
