# Generated by Django 5.1.4 on 2026-04-30 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_create_role_groups'),
        ('periods', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_kind', models.CharField(choices=[('person', 'Person'), ('company', 'Company')], max_length=10)),
                ('to_kind', models.CharField(choices=[('person', 'Person'), ('company', 'Company')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=14)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=12)),
                ('auto_generated', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transfers', to='accounts.person')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='periods.month')),
                ('to_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfers', to='accounts.person')),
            ],
            options={
                'ordering': ('-month__year', '-month__month', 'status', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=14)),
                ('happened_on', models.DateField()),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('proof', models.FileField(blank=True, null=True, upload_to='proofs/%Y/%m/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='transfers.transfer')),
            ],
            options={
                'ordering': ('-happened_on', '-id'),
            },
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['status'], name='transfers_t_status_91e571_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['month', 'status'], name='transfers_t_month_i_1de69e_idx'),
        ),
    ]
