# Generated by Django 5.1.4 on 2026-04-30 11:29

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_create_role_groups'),
        ('periods', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Earning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_kind', models.CharField(choices=[('person', 'Person'), ('company', 'Company')], default='person', max_length=10)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=14)),
                ('received_on', models.DateField()),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('earner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='earnings', to='accounts.person')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='earnings', to='periods.month')),
                ('receiver_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_earnings', to='accounts.person')),
            ],
            options={
                'ordering': ('-received_on', '-id'),
            },
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_company', models.BooleanField(default=False)),
                ('percent', models.PositiveSmallIntegerField()),
                ('amount', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='accounts.person')),
                ('earning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='earnings.earning')),
            ],
            options={
                'ordering': ('-is_company', 'person__name'),
            },
        ),
        migrations.AddIndex(
            model_name='earning',
            index=models.Index(fields=['month', 'earner'], name='earnings_ea_month_i_55e173_idx'),
        ),
        migrations.AddConstraint(
            model_name='allocation',
            constraint=models.UniqueConstraint(condition=models.Q(('person__isnull', False)), fields=('earning', 'person'), name='earnings_alloc_unique_person'),
        ),
        migrations.AddConstraint(
            model_name='allocation',
            constraint=models.UniqueConstraint(condition=models.Q(('is_company', True)), fields=('earning',), name='earnings_alloc_unique_company'),
        ),
    ]
