# Generated by Django 5.1.4 on 2026-04-30 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earnings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='earning',
            name='project',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
