# Generated by Django 5.1.4 on 2026-04-30 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earnings', '0002_earning_project'),
        ('periods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earning',
            name='month',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='earnings', to='periods.month'),
        ),
    ]
