# Generated by Django 5.1.4 on 2026-04-30 11:23

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Company', max_length=120)),
                ('opening_balance', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('opening_balance_date', models.DateField(blank=True, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=120)),
                ('bank_account_title', models.CharField(blank=True, max_length=120)),
                ('bank_account_number', models.CharField(blank=True, max_length=64)),
                ('bank_iban', models.CharField(blank=True, max_length=64, verbose_name='Bank IBAN')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Company',
            },
        ),
        migrations.CreateModel(
            name='BalanceMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('adjustment', 'Adjustment'), ('expense', 'Expense'), ('receipt', 'Receipt from settlement'), ('payout', 'Payout to person')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=14)),
                ('happened_on', models.DateField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('source_app', models.CharField(blank=True, max_length=40)),
                ('source_model', models.CharField(blank=True, max_length=40)),
                ('source_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='company.company')),
            ],
            options={
                'ordering': ('-happened_on', '-id'),
                'indexes': [models.Index(fields=['happened_on'], name='company_bal_happene_84ab72_idx'), models.Index(fields=['kind'], name='company_bal_kind_992194_idx'), models.Index(fields=['source_app', 'source_model', 'source_id'], name='company_bal_source__317fe9_idx')],
            },
        ),
    ]
