# Generated by Django 5.1.4 on 2026-04-30 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('happened_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('action', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted')], max_length=10)),
                ('object_id', models.PositiveBigIntegerField()),
                ('object_repr', models.CharField(max_length=255)),
                ('changed_fields', models.JSONField(blank=True, default=dict)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ('-happened_at', '-id'),
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='audit_audit_content_4c2ead_idx'), models.Index(fields=['action'], name='audit_audit_action_86e815_idx')],
            },
        ),
    ]
